export const actionTypes = {
  ui: {
    SET_NOTIFICATION_STATE: 'SET_NOTIFICATION_STATE',
    SET_PLAYLIST_STATE: 'SET_PLAYLIST_STATE',
    SET_DIALOG_STATE: 'SET_DIALOG_STATE',
    SET_PLAYER_STATE: 'SET_PLAYER_STATE',
    SET_SIGNUP_STATE: 'SET_SIGNUP_STATE',
    SET_LOGIN_STATE: 'SET_LOGIN_STATE',
    SET_HOMEPAGE_STATE: 'SET_HOMEPAGE_STATE'
  },
  video: {
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    NEXT_PAGE: 'NEXT_PAGE',
    GET_PLAYER: 'GET_PLAYER',
    SET_VIDEOS: 'SET_VIDEOS',
    SELECT: 'SELECT',
    PAUSE: 'PAUSE',
    PLAY: 'PLAY',
    PREVIOUS: 'PREVIOUS',
    NEXT: 'NEXT',
    REPLAY: 'REPLAY'
  },
  playlist: {
    ADD: 'ADD',
    REMOVE: 'REMOVE'
  },
  auth: {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOGOUT: "LOGOUT",
    SET_EMAIL_VALUE: "SET_EMAIL_VALUE",
    SET_PASSWORD_VALUE: "SET_PASSWORD_VALUE"
  }
}